#   _______ _           _                 ______
#  |__   __(_)         | |               |___  /
#     | |   _ _ __ ___ | |__   ___ _ __     / /
#     | |  | | '_ ` _ \| '_ \ / _ \ '__|   / /
#     | |  | | | | | | | |_) |  __/ |     / /__
#     |_|  |_|_| |_| |_|_.__/ \___|_|    /_____|

# === COLOR CODES ===
# This plugin supports old color codes like: &c, &l, &o, etc.
# It also supports MiniMessage, a more advanced way to format messages:
# https://docs.advntr.dev/minimessage/format.html
# With MiniMessage, you can add HEX colors, gradients, hover and click events, etc.


# === GENERAL SETTINGS ===

# If set to true, LifeStealZ will check for updates and let you know if there's a newer version
checkForUpdates: true

# Set the language to any code found in the "lang" folder (don't add the .yml extension)
# You can add your own language files. Use https://github.com/KartoffelChipss/LifeStealZ/tree/main/src/main/resources/lang/en-US.yml as a template
# If you want to help translating the plugin, please refer to this article: https://lsz.strassburger.dev/contributing/localization
#  | en-US | de-DE | es-ES | fr-FR | cs-CZ | vi-VN | zh-CN | pl-PL | nl-NL | ru-RU
lang: "en-US"

# The accent color of the plugin. This color replaces %ac% in the lang files.
accentColor: "<#00D26A>"