#   _______ _           _                 ______
#  |__   __(_)         | |               |___  /
#     | |   _ _ __ ___ | |__   ___ _ __     / /
#     | |  | | '_ ` _ \| '_ \ / _ \ '__|   / /
#     | |  | | | | | | | |_) |  __/ |     / /__
#     |_|  |_|_| |_| |_|_.__/ \___|_|    /_____|

# === COLOR CODES ===
# This plugin supports old color codes like: &c, &l, &o, etc.
# It also supports MiniMessage, a more advanced way to format messages:
# https://docs.advntr.dev/minimessage/format.html
# With MiniMessage, you can add HEX colors, gradients, hover and click events, etc.


# === GENERAL SETTINGS ===

# If set to true, LifeStealZ will check for updates and let you know if there's a newer version
checkForUpdates: true

# Set the language to any code found in the "lang" folder (don't add the .yml extension)
# You can add your own language files. Use https://github.com/ZetaPlugins/TimberZ/tree/main/src/main/resources/lang/en-US.yml as a template
# If you want to help translating the plugin, please refer to this article: https://docs.zetaplugins.com/#contributing
#  | en-US | de-DE |
lang: "en-US"

# The accent color of the plugin. This color replaces %ac% in the lang files.
accentColor: "<#00D26A>"


# === TIMBER SETTINGS ===

# If set to true, players can enable or disable timber mode by pressing F with a qualifying axe in hand
toggleTimber: true

# If set to true, you can only use axes with a customModelData value in the list below
restrictAxes: false

# If restrictAxes is set to true, you can only use axes with a customModelData value in this list
allowedModelData:
  - 100

# If set to true, TimberZ will replant the tree after cutting it down
replant: true

# Modify how much durability is removed from the axe when cutting down a tree
# Formula: logCount * durabilityMultiplier
durabilityMultiplier: 1.0

# The minimum durability the axe must have after cutting down a tree
minDurability: 10


# === TREE DETECTION ===

# Only change these settings if you know what you are doing!
# These are used to detect trees and their leaves and are already fine tuned.

leavesSearchRadius: 4
maxTreeSize: 500
maxSearchRadius: 1
diagonalSearchRange: 2
minLeavesRequired: 5
minLogsRequired: 3