name: TimberZ
version: '${version}'
main: com.zetaplugins.timberz.TimberZ
bootstrapper: com.zetaplugins.timberz.bootstrap.TimberZBootstrap
api-version: '1.21'
load: STARTUP
authors: [ ZetaPlugins ]
website: https://zetaplugins.com/
description: TimberZ - The Ultimate Timber and Lumberjack axe plugin!

permissions:
    timberz.admin:
        default: op
        description: Allows the user to manage the plugin
    timberz.useTimber:
        default: true
        description: Allows the user to use the TimberZ feature